name: min
on:
  workflow_call:
    inputs:
      msg:
        type: string
        default: 'hi'
jobs:
  m:
    runs-on: ubuntu-latest
    steps:
      - env:
          MSG: ${{ inputs.msg }}
        run: echo "min ran: $MSG"
